### PR TITLE
Manifest v2 + update to latest upstream.

### PR DESCRIPTION
**Pull request by orhtej2**
## Problem

- Upstream outdated

## Solution

- Update to latest upstream
- Use packaging v2

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by orhtej2** [comment]
!testme !bookwormtestme

**Comment by orhtej2** [comment]
Update leaves dangling php fpm config, do not merge

**Comment by orhtej2** [comment]
!testme !bookwormtestme

**Comment by orhtej2** [comment]
!testme !bookwormtestme

**Comment by Salamandar** [comment]
LGTM, let’s merge it !

**Comment by Salamandar** [comment]
Ooops, that was actually manually merged, it should have been automatically closed :D

**Comment by orhtej2** [comment]
It was not, current `master` is broken compared to demo page and pulls assets straight from Framasoft.

**Pull request closed without merging**
